services:
  notes_db:
    image: postgres:14
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: [ '${POSTGRES_PORT}:5432' ]
    networks:
      - notes_network

  notes_redis:
    image: redis:6.2-alpine
    container_name: notes_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=10
    networks:
      - notes_network
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/redis-data

networks:
  default:
    driver: bridge
  notes_network:
    name: notes_network

volumes:
  db_data:
  redis_data: